INSERT INTO _countries (country_name, country_code, dialing_code, currency_code, internet_tld) VALUES
('Afghanistan', 'AF', '+93', 'AFN', '.af'),
('Albania', 'AL', '+355', 'ALL', '.al'),
('Algeria', 'DZ', '+213', 'DZD', '.dz'),
('Andorra', 'AD', '+376', 'EUR', '.ad'),
('Angola', 'AO', '+244', 'AOA', '.ao'),
('Antigua and Barbuda', 'AG', '+1-268', 'XCD', '.ag'),
('Argentina', 'AR', '+54', 'ARS', '.ar'),
('Armenia', 'AM', '+374', 'AMD', '.am'),
('Australia', 'AU', '+61', 'AUD', '.au'),
('Austria', 'AT', '+43', 'EUR', '.at'),
('Azerbaijan', 'AZ', '+994', 'AZN', '.az'),
('Bahamas', 'BS', '+1-242', 'BSD', '.bs'),
('Bahrain', 'BH', '+973', 'BHD', '.bh'),
('Bangladesh', 'BD', '+880', 'BDT', '.bd'),
('Barbados', 'BB', '+1-246', 'BBD', '.bb'),
('Belarus', 'BY', '+375', 'BYN', '.by'),
('Belgium', 'BE', '+32', 'EUR', '.be'),
('Belize', 'BZ', '+501', 'BZD', '.bz'),
('Benin', 'BJ', '+229', 'XOF', '.bj'),
('Bhutan', 'BT', '+975', 'BTN', '.bt'),
('Bolivia', 'BO', '+591', 'BOB', '.bo'),
('Bosnia and Herzegovina', 'BA', '+387', 'BAM', '.ba'),
('Botswana', 'BW', '+267', 'BWP', '.bw'),
('Brazil', 'BR', '+55', 'BRL', '.br'),
('Brunei', 'BN', '+673', 'BND', '.bn'),
('Bulgaria', 'BG', '+359', 'BGN', '.bg'),
('Burkina Faso', 'BF', '+226', 'XOF', '.bf'),
('Burundi', 'BI', '+257', 'BIF', '.bi'),
('Cabo Verde', 'CV', '+238', 'CVE', '.cv'),
('Cambodia', 'KH', '+855', 'KHR', '.kh'),
('Cameroon', 'CM', '+237', 'XAF', '.cm'),
('Canada', 'CA', '+1', 'CAD', '.ca'),
('Central African Republic', 'CF', '+236', 'XAF', '.cf'),
('Chad', 'TD', '+235', 'XAF', '.td'),
('Chile', 'CL', '+56', 'CLP', '.cl'),
('China', 'CN', '+86', 'CNY', '.cn'),
('Colombia', 'CO', '+57', 'COP', '.co'),
('Comoros', 'KM', '+269', 'KMF', '.km'),
('Congo, Democratic Republic of the', 'CD', '+243', 'CDF', '.cd'),
('Congo, Republic of the', 'CG', '+242', 'XAF', '.cg'),
('Costa Rica', 'CR', '+506', 'CRC', '.cr'),
('Croatia', 'HR', '+385', 'HRK', '.hr'),
('Cuba', 'CU', '+53', 'CUP', '.cu'),
('Cyprus', 'CY', '+357', 'EUR', '.cy'),
('Czech Republic', 'CZ', '+420', 'CZK', '.cz'),
('Denmark', 'DK', '+45', 'DKK', '.dk'),
('Djibouti', 'DJ', '+253', 'DJF', '.dj'),
('Dominica', 'DM', '+1-767', 'XCD', '.dm'),
('Dominican Republic', 'DO', '+1-809', 'DOP', '.do'),
('Ecuador', 'EC', '+593', 'USD', '.ec'),
('Egypt', 'EG', '+20', 'EGP', '.eg'),
('El Salvador', 'SV', '+503', 'USD', '.sv'),
('Equatorial Guinea', 'GQ', '+240', 'XAF', '.gq'),
('Eritrea', 'ER', '+291', 'ERN', '.er'),
('Estonia', 'EE', '+372', 'EUR', '.ee'),
('Eswatini', 'SZ', '+268', 'SZL', '.sz'),
('Ethiopia', 'ET', '+251', 'ETB', '.et'),
('Fiji', 'FJ', '+679', 'FJD', '.fj'),
('Finland', 'FI', '+358', 'EUR', '.fi'),
('France', 'FR', '+33', 'EUR', '.fr'),
('Gabon', 'GA', '+241', 'XAF', '.ga'),
('Gambia', 'GM', '+220', 'GMD', '.gm'),
('Georgia', 'GE', '+995', 'GEL', '.ge'),
('Germany', 'DE', '+49', 'EUR', '.de'),
('Ghana', 'GH', '+233', 'GHS', '.gh'),
('Greece', 'GR', '+30', 'EUR', '.gr'),
('Grenada', 'GD', '+1-473', 'XCD', '.gd'),
('Guatemala', 'GT', '+502', 'GTQ', '.gt'),
('Guinea', 'GN', '+224', 'GNF', '.gn'),
('Guinea-Bissau', 'GW', '+245', 'XOF', '.gw'),
('Guyana', 'GY', '+592', 'GYD', '.gy'),
('Haiti', 'HT', '+509', 'HTG', '.ht'),
('Honduras', 'HN', '+504', 'HNL', '.hn'),
('Hungary', 'HU', '+36', 'HUF', '.hu'),
('Iceland', 'IS', '+354', 'ISK', '.is'),
('India', 'IN', '+91', 'INR', '.in'),
('Indonesia', 'ID', '+62', 'IDR', '.id'),
('Iran', 'IR', '+98', 'IRR', '.ir'),
('Iraq', 'IQ', '+964', 'IQD', '.iq'),
('Ireland', 'IE', '+353', 'EUR', '.ie'),
('Israel', 'IL', '+972', 'ILS', '.il'),
('Italy', 'IT', '+39', 'EUR', '.it'),
('Jamaica', 'JM', '+1-876', 'JMD', '.jm'),
('Japan', 'JP', '+81', 'JPY', '.jp'),
('Jordan', 'JO', '+962', 'JOD', '.jo'),
('Kazakhstan', 'KZ', '+7', 'KZT', '.kz'),
('Kenya', 'KE', '+254', 'KES', '.ke'),
('Kiribati', 'KI', '+686', 'AUD', '.ki'),
('Korea, North', 'KP', '+850', 'KPW', '.kp'),
('Korea, South', 'KR', '+82', 'KRW', '.kr'),
('Kuwait', 'KW', '+965', 'KWD', '.kw'),
('Kyrgyzstan', 'KG', '+996', 'KGS', '.kg'),
('Laos', 'LA', '+856', 'LAK', '.la'),
('Latvia', 'LV', '+371', 'EUR', '.lv'),
('Lebanon', 'LB', '+961', 'LBP', '.lb'),
('Lesotho', 'LS', '+266', 'LSL', '.ls'),
('Liberia', 'LR', '+231', 'LRD', '.lr'),
('Libya', 'LY', '+218', 'LYD', '.ly'),
('Liechtenstein', 'LI', '+423', 'CHF', '.li'),
('Lithuania', 'LT', '+370', 'EUR', '.lt'),
('Luxembourg', 'LU', '+352', 'EUR', '.lu'),
('Madagascar', 'MG', '+261', 'MGA', '.mg'),
('Malawi', 'MW', '+265', 'MWK', '.mw'),
('Malaysia', 'MY', '+60', 'MYR', '.my'),
('Maldives', 'MV', '+960', 'MVR', '.mv'),
('Mali', 'ML', '+223', 'XOF', '.ml'),
('Malta', 'MT', '+356', 'EUR', '.mt'),
('Marshall Islands', 'MH', '+692', 'USD', '.mh'),
('Mauritania', 'MR', '+222', 'MRU', '.mr'),
('Mauritius', 'MU', '+230', 'MUR', '.mu'),
('Mexico', 'MX', '+52', 'MXN', '.mx'),
('Micronesia', 'FM', '+691', 'USD', '.fm'),
('Moldova', 'MD', '+373', 'MDL', '.md'),
('Monaco', 'MC', '+377', 'EUR', '.mc'),
('Mongolia', 'MN', '+976', 'MNT', '.mn'),
('Montenegro', 'ME', '+382', 'EUR', '.me'),
('Morocco', 'MA', '+212', 'MAD', '.ma'),
('Mozambique', 'MZ', '+258', 'MZN', '.mz'),
('Myanmar', 'MM', '+95', 'MMK', '.mm'),
('Namibia', 'NA', '+264', 'NAD', '.na'),
('Nauru', 'NR', '+674', 'AUD', '.nr'),
('Nepal', 'NP', '+977', 'NPR', '.np'),
('Netherlands', 'NL', '+31', 'EUR', '.nl'),
('New Zealand', 'NZ', '+64', 'NZD', '.nz'),
('Nicaragua', 'NI', '+505', 'NIO', '.ni'),
('Niger', 'NE', '+227', 'XOF', '.ne'),
('Nigeria', 'NG', '+234', 'NGN', '.ng'),
('North Macedonia', 'MK', '+389', 'MKD', '.mk'),
('Norway', 'NO', '+47', 'NOK', '.no'),
('Oman', 'OM', '+968', 'OMR', '.om'),
('Pakistan', 'PK', '+92', 'PKR', '.pk'),
('Palau', 'PW', '+680', 'USD', '.pw'),
('Palestine', 'PS', '+970', 'ILS', '.ps'),
('Panama', 'PA', '+507', 'PAB', '.pa'),
('Papua New Guinea', 'PG', '+675', 'PGK', '.pg'),
('Paraguay', 'PY', '+595', 'PYG', '.py'),
('Peru', 'PE', '+51', 'PEN', '.pe'),
('Philippines', 'PH', '+63', 'PHP', '.ph'),
('Poland', 'PL', '+48', 'PLN', '.pl'),
('Portugal', 'PT', '+351', 'EUR', '.pt'),
('Qatar', 'QA', '+974', 'QAR', '.qa'),
('Romania', 'RO', '+40', 'RON', '.ro'),
('Russia', 'RU', '+7', 'RUB', '.ru'),
('Rwanda', 'RW', '+250', 'RWF', '.rw'),
('Saint Kitts and Nevis', 'KN', '+1-869', 'XCD', '.kn'),
('Saint Lucia', 'LC', '+1-758', 'XCD', '.lc'),
('Saint Vincent and the Grenadines', 'VC', '+1-784', 'XCD', '.vc'),
('Samoa', 'WS', '+685', 'WST', '.ws'),
('San Marino', 'SM', '+378', 'EUR', '.sm'),
('Sao Tome and Principe', 'ST', '+239', 'STN', '.st'),
('Saudi Arabia', 'SA', '+966', 'SAR', '.sa'),
('Senegal', 'SN', '+221', 'XOF', '.sn'),
('Serbia', 'RS', '+381', 'RSD', '.rs'),
('Seychelles', 'SC', '+248', 'SCR', '.sc'),
('Sierra Leone', 'SL', '+232', 'SLL', '.sl'),
('Singapore', 'SG', '+65', 'SGD', '.sg'),
('Slovakia', 'SK', '+421', 'EUR', '.sk'),
('Slovenia', 'SI', '+386', 'EUR', '.si'),
('Solomon Islands', 'SB', '+677', 'AUD', '.sb'),
('Somalia', 'SO', '+252', 'SOS', '.so'),
('South Africa', 'ZA', '+27', 'ZAR', '.za'),
('South Sudan', 'SS', '+211', 'SSP', '.ss'),
('Spain', 'ES', '+34', 'EUR', '.es'),
('Sri Lanka', 'LK', '+94', 'LKR', '.lk'),
('Sudan', 'SD', '+249', 'SDG', '.sd'),
('Suriname', 'SR', '+597', 'SRD', '.sr'),
('Sweden', 'SE', '+46', 'SEK', '.se'),
('Switzerland', 'CH', '+41', 'CHF', '.ch'),
('Syria', 'SY', '+963', 'SYP', '.sy'),
('Taiwan', 'TW', '+886', 'TWD', '.tw'),
('Tajikistan', 'TJ', '+992', 'TJS', '.tj'),
('Tanzania', 'TZ', '+255', 'TZS', '.tz'),
('Thailand', 'TH', '+66', 'THB', '.th'),
('Timor-Leste', 'TL', '+670', 'USD', '.tl'),
('Togo', 'TG', '+228', 'XOF', '.tg'),
('Tonga', 'TO', '+676', 'TOP', '.to'),
('Trinidad and Tobago', 'TT', '+1-868', 'TTD', '.tt'),
('Tunisia', 'TN', '+216', 'TND', '.tn'),
('Turkey', 'TR', '+90', 'TRY', '.tr'),
('Turkmenistan', 'TM', '+993', 'TMT', '.tm'),
('Tuvalu', 'TV', '+688', 'AUD', '.tv'),
('Uganda', 'UG', '+256', 'UGX', '.ug'),
('Ukraine', 'UA', '+380', 'UAH', '.ua'),
('United Arab Emirates', 'AE', '+971', 'AED', '.ae'),
('United Kingdom', 'GB', '+44', 'GBP', '.uk'),
('United States', 'US', '+1', 'USD', '.us'),
('Uruguay', 'UY', '+598', 'UYU', '.uy'),
('Uzbekistan', 'UZ', '+998', 'UZS', '.uz'),
('Vanuatu', 'VU', '+678', 'VUV', '.vu'),
('Vatican City', 'VA', '+379', 'EUR', '.va'),
('Venezuela', 'VE', '+58', 'VES', '.ve'),
('Vietnam', 'VN', '+84', 'VND', '.vn'),
('Yemen', 'YE', '+967', 'YER', '.ye'),
('Zambia', 'ZM', '+260', 'ZMW', '.zm'),
('Zimbabwe', 'ZW', '+263', 'ZWL', '.zw');