spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/learn
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    redis:
      host: redis
      port: 6379
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8089/realms/petApp
          jwk-set-uri: http://localhost:8089/realms/petApp/protocol/openid-connect/certs

logging:
  level:
    root: INFO
    com.tapiwa.demo: DEBUG


server:
  port: 8185
  servlet:
    context-path: /api/v1