spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/learn
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    redis:
      host: redis
      port: 6379

logging:
  level:
    root: INFO
    com.tapiwa.demo: DEBUG