name: Build and Test

on:
    push:
        branches:
        - with-github-actions
    pull_request:
        branches:
        - with-github-actions


jobs:
    build:
        runs-on: ubuntu-latest


        services:
            postgres:
                image: postgres:latest
                env:
                    POSTGRES_USER: 'admin'
                    POSTGRES_PASSWORD: 'admin'
                    POSTGRES_DB: learn
                ports:
                    - 5432:5432
                options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5


        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Set up JDK 17
              uses: actions/setup-java@v1
              with:
                java-version: 17

            - name: Cache Maven packages
              uses: actions/cache@v4
              with:
                  path: ~/.m2
                  key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
                  restore-keys: ${{ runner.os }}-maven

            - name: Wait for Postgres to be ready
              run: while ! pg_isready -h localhost -U learn; do sleep 5; done


            - name: Run maven
              run: mvn -B -ntp clean install

            - name: Save jar file
              uses: actions/upload-artifact@v2
              with:
                    name: Build Artifact
                    path: target/*.jar